export default [
  {
    workoutId: 1,
    title: 'Barbell Bench press',
    description: 'classic bench press',
    type: 'strenght',
    reps: 8,
    weight: 55,
    timeRest: 200,
    muscleGroup: 'chest',
  },
  {
    workoutId: 1,
    title: 'Dumbbell Bench Press',
    description: 'classic bench press but with dumbells',
    type: 'strenght',
    reps: 8,
    weight: 12,
    muscleGroup: 'chest',
  },
  {
    workoutId: 2,
    title: 'Run in place',
    description: 'just run in place',
    type: 'cardio',
    timeAction: 60,
    timeRest: 20,
    weight: 12,
    muscleGroup: 'legs',
  },
  {
    workoutId: 3,
    title: 'Pull-ups',
    description: 'classic pull-ups',
    type: 'strenght',
    reps: 12,
    timeRest: 200,
    muscleGroup: 'back',
  },
  {
    workoutId: 3,
    title: 'Pull-fucks',
    description: 'pull-ups but with fucking',
    type: 'vitality',
    reps: 12,
    timeRest: 200,
    muscleGroup: 'dick',
  },
];
